### ISSUE TITLE
Cannot destructure property `hasChanges`

### ISSUE THREAD

**Issue by FabioRosado** [gr2m/create-or-update-pull-request-action#209]
Hello,

Thank you for creating this action, I'm using github actions for the first time so I guess there is a lot I don't understand. 

I'm trying to create an action that runs black linting to a python project.

This is my actions file

```yaml
name: lint

on: 
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: rocioar/gradual-black-formatter@v1
      - uses: gr2m/create-or-update-pull-request-action@v1.2.2
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }
```

But when commit a change/open a PR, this action fails with:

```
Run gr2m/create-or-update-pull-request-action@v1.2.2
##[error]Cannot destructure property `hasChanges` of 'undefined' or 'null'.
```

Any idea what I am doing wrong or did I found a bug?

Thank you for you time.
