### ISSUE TITLE
Action fails with error File not found: '/home/runner/work/_actions/gr2m/create-or-update-pull-request-action/v1.5.1/dist/index.js'

### ISSUE THREAD

**Issue by localheinz** [gr2m/create-or-update-pull-request-action#350]
With the following workflow definition

```yaml
# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Update"

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 9 * * *"

jobs:
  schema:
    name: "Schema"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "7.2"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.4.0"

      - name: "Set up PHP"
        uses: "shivammathur/setup-php@2.15.0"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"

      - name: "Download schema"
        run: "wget --output-document=resource/schema.json https://getcomposer.org/schema.json"

      - name: "Show diff"
        run: "git diff resource/schema.json"

      - name: "Laxify schema"
        run: "php bin/laxify-schema.php"

      - name: "Open pull request updating schema"
        uses: "gr2m/create-or-update-pull-request-action@v1.5.1"
        with:
          author: "ergebnis-bot <bot@ergebn.is>"
          branch: "feature/schema"
          body: |
            This PR

            * [x] updates `schema.json`
          commit-message: "Enhancement: Update schema.json"
          path: "resource/"
          title: "Enhancement: Update schema.json"
        env:
          GITHUB_TOKEN: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
```

the action currently fails with

```
Error: File not found: '/home/runner/work/_actions/gr2m/create-or-update-pull-request-action/v1.5.1/dist/index.js'
```

For reference, see https://github.com/ergebnis/composer-normalize/runs/4285206560?check_suite_focus=true#step:7:14.
