### ISSUE TITLE
Question: one different PR per modified file

### ISSUE THREAD

**Issue by mirpedrol** [gr2m/create-or-update-pull-request-action#503]
Hello,

I would like to use this GHA together with [dorny/paths-filter@v2](https://github.com/dorny/paths-filter) to generate one different PR for each modified file. Would this be possible?

By now I have one action that modifies some files, drony's action that checks which files are modified and this action to create a PR:

```
name: Update
on:
  pull_request:
    branches: [master]

jobs:
  update_modules:
    name: update modules
    runs-on: ubuntu-20.04
    outputs:
      # Expose matched filters as job 'modules' output variable
      modules: ${{ steps.filter.outputs.update_modules }}
    steps:
      - uses: actions/checkout@v2

     < code that modifies files >

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          # Detect staged and unstaged local changes
          base: HEAD
          filters: "tests/config/modules.yml"

  push_changes:
    runs-on: ubuntu-latest
    name: Update module ${{ matrix.tags }} version
    needs: update_modules
    if: needs.update_modules.outputs.modules != '[]'
    strategy:
      fail-fast: false
      matrix:
        tags: ["${{ fromJson(needs.update_modules.outputs.modules) }}"]
    steps:
      # Use the token to check out so we can push later
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.bot_auth_token }}
          persist-credentials: false

      - uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.bot_auth_token }}
        with:
          title: "Update module ${{ matrix.tags }} version"
          branch: "${{ matrix.tags }}"
          path: "${{ matrix.tags }}"
          commit-message: "Update module ${{ matrix.tags }} version"
          author: "bot"
          update-pull-request-title-and-body: false
```

Is there an option that would allow pushing changes only from particular paths passed through the `matrix.tags`?

Thank you very much for your help!
